title: default
'@extends':
    type: default

form:
    fields:
        tabs:
            type: tabs
            active: 1
            fields:
                content:
                    fields:
                        header.subheading:
                            type: text
                            label: THEME_CLEAN_BLOG.ADMIN.SUBHEADING.LABEL
                            help: THEME_CLEAN_BLOG.ADMIN.SUBHEADING.HELP
                        header.header_image:
                            type: filepicker
                            folder: 'theme@:/img'
                            preview_images: true
                            acccept:
                                - .png
                                - .jpg
                            label: THEME_CLEAN_BLOG.ADMIN.HEADER_IMAGE.LABEL
                            help: THEME_CLEAN_BLOG.ADMIN.HEADER_IMAGE.HELP
